Repository AiursoftWeb/Kahla.App, pull requests merged in 2019-08, with the labels that each got.

#605 Release 3.6.3
  README.md
  package-lock.json
  package.json
  src/app/Controllers/friends.component.ts
  src/app/Controllers/header.component.ts
  src/app/Controllers/localSearch.component.ts
  src/app/Controllers/share.component.ts
  src/app/Controllers/talking.component.ts
  src/app/Models/Message.ts
  src/app/Modules/AppRoutingModule.ts
  src/app/Services/MessageService.ts
  src/app/Services/ShareService.ts
  src/app/Services/UploadService.ts
  src/app/Styles/friends.scss
  src/app/Styles/talking.scss
  src/app/Views/conversations.html
  src/app/Views/header.html
  src/app/Views/home.html
  src/app/Views/localSearch.html
  src/app/Views/share.html
  src/app/Views/talking.html
  src/app/app.module.ts
  src/manifest.json
Labels: New release

#608 Prevent the app to rotate.
  src/manifest.json
Labels: Invalid design

#612 Use black-translucent for apple
  src/index.html
Labels: Enhancement required

#621 Allow group with space.
  src/app/Controllers/friends.component.ts
Labels: Invalid design

#623 Release 3.6.4
  README.md
  package.json
  src/app/Controllers/about.component.ts
  src/app/Controllers/add-friend.component.ts
  src/app/Controllers/advanced-setting.component.ts
  src/app/Controllers/app.component.ts
  src/app/Controllers/discover.component.ts
  src/app/Controllers/friends.component.ts
  src/app/Controllers/group.component.ts
  src/app/Controllers/manageGroup.component.ts
  src/app/Controllers/settings.component.ts
  src/app/Controllers/talking.component.ts
  src/app/Controllers/user.component.ts
  src/app/Controllers/userDetail.component.ts
  src/app/Models/ContactInfo.ts
  src/app/Models/Conversation.ts
  src/app/Models/FilePath.ts
  src/app/Models/GroupConversation.ts
  src/app/Models/GroupsResults.ts
  src/app/Models/KahlaUser.ts
  src/app/Models/Timers.ts
  src/app/Models/UploadFile.ts
  src/app/Services/AuthApiService.ts
  src/app/Services/CacheService.ts
  src/app/Services/FilesApiService.ts
  src/app/Services/GroupsApiService.ts
  src/app/Services/HomeService.ts
  src/app/Services/InitService.ts
  src/app/Services/MessageService.ts
  src/app/Services/TimerService.ts
  src/app/Services/UploadService.ts
  src/app/Views/about.html
  src/app/Views/app.html
  src/app/Views/talking.html
  src/app/values.ts
  src/assets/192x192.png
  src/index.html
  src/manifest.json
  src/sw.js
Labels: New release

#635 Hide the cancel button in friends component when user input is empty.
  src/app/Styles/add-friend.scss
  src/app/Styles/menu.scss
  src/app/Views/friends.html
Labels: Enhancement required

#643 Better place for pining Kahla to home.
  src/app/Controllers/about.component.ts
  src/app/Controllers/settings.component.ts
  src/app/Views/about.html
  src/app/Views/settings.html
Labels: Low priority

#646 Ctrl remove
  README.md
  src/app/Controllers/friends.component.ts
  src/app/Views/friends.html
Labels: Enhancement required, Invalid design

#648 Release 3.7.0
  .editorconfig
  README.md
  package-lock.json
  package.json
  src/app/Controllers/about.component.ts
  src/app/Controllers/add-friend.component.ts
  src/app/Controllers/advanced-setting.component.ts
  src/app/Controllers/app.component.ts
  src/app/Controllers/conversations.component.ts
  src/app/Controllers/devices.component.ts
  src/app/Controllers/discover.component.ts
  src/app/Controllers/friends.component.ts
  src/app/Controllers/group.component.ts
  src/app/Controllers/localSearch.component.ts
  src/app/Controllers/manageGroup.component.ts
  src/app/Controllers/register.component.ts
  src/app/Controllers/settings.component.ts
  src/app/Controllers/share.component.ts
  src/app/Controllers/signin.component.ts
  src/app/Controllers/talking.component.ts
  src/app/Controllers/theme.component.ts
  src/app/Controllers/user.component.ts
  src/app/Controllers/userDetail.component.ts
  src/app/Models/CacheModel.ts
  src/app/Models/Message.ts
  src/app/Models/NewMessageEvent.ts
  src/app/Modules/AppRoutingModule.ts
  src/app/Services/CacheService.ts
  src/app/Services/FriendshipService.ts
  src/app/Services/GroupsApiService.ts
  src/app/Services/HomeService.ts
  src/app/Services/InitService.ts
  src/app/Services/MessageService.ts
  src/app/Services/ShareService.ts
  src/app/Services/ThemeService.ts
  src/app/Services/TimerService.ts
  src/app/Services/UploadService.ts
  src/app/Styles/_shared.scss
  src/app/Styles/add-friend.scss
  src/app/Styles/app.scss
  src/app/Styles/friends.scss
  src/app/Styles/menu.scss
  src/app/Styles/talking.scss
  src/app/Views/about.html
  src/app/Views/add-friend.html
  src/app/Views/app.html
  src/app/Views/conversations.html
  src/app/Views/friends.html
  src/app/Views/group.html
  src/app/Views/home.html
  src/app/Views/localSearch.html
  src/app/Views/settings.html
  src/app/Views/share.html
  src/app/Views/talking.html
  src/app/Views/user.html
  src/app/app.module.ts
  src/app/values.ts
  src/index.html
  src/sw.js
Labels: New release

#651 fix: change the preconnect api server url
  src/index.html
Labels: Enhancement required

#652 Use a better way to copy your f**king assetlinks.json
  angular.json
  copy-assetlinks.sh
  package.json
  src/assetlinks.json
Labels: Enhancement required
