Repository AiursoftWeb/Kahla.App, pull requests merged in 2019-03, with the labels that each got.

#270 Upgrade api level and make some small changes to devices component.
  package.json
  src/app/Controllers/devices.component.ts
Labels: Enhancement

#272 Add dark theme for kahla
  angular.json
  src/app/Controllers/app.component.ts
  src/app/Controllers/theme.component.ts
  src/app/Models/Themes.ts
  src/app/Modules/AppRoutingModule.ts
  src/app/Styles/add-friend.css
  src/app/Styles/conversations.css
  src/app/Styles/friendrequests.css
  src/app/Styles/friends.css
  src/app/Styles/index.css
  src/app/Styles/menu.css
  src/app/Styles/nav.css
  src/app/Styles/talking.css
  src/app/Styles/toggleButton.css
  src/app/Styles/userDetail.css
  src/app/Views/settings.html
  src/app/Views/theme.html
  src/app/app.module.ts
  src/index.html
Labels: Enhancement

#271 Release 3.0.0 with new push system
  .gitignore
  angular.json
  package-lock.json
  package.json
  src/app/Controllers/app.component.ts
  src/app/Controllers/devices.component.ts
  src/app/Controllers/friendrequests.component.ts
  src/app/Controllers/settings.component.ts
  src/app/Controllers/signin.component.ts
  src/app/Controllers/theme.component.ts
  src/app/Models/CacheModel.ts
  src/app/Models/Device.ts
  src/app/Models/NewMessageEvent.ts
  src/app/Models/Themes.ts
  src/app/Modules/AppRoutingModule.ts
  src/app/Services/AuthApiService.ts
  src/app/Services/CacheService.ts
  src/app/Services/CheckService.ts
  src/app/Services/InitService.ts
  src/app/Services/MessageService.ts
  src/app/Services/Notify.ts
  src/app/Styles/add-friend.css
  src/app/Styles/button.css
  src/app/Styles/conversations.css
  src/app/Styles/friendrequests.css
  src/app/Styles/friends.css
  src/app/Styles/header.css
  src/app/Styles/index.css
  src/app/Styles/menu.css
  src/app/Styles/nav.css
  src/app/Styles/talking.css
  src/app/Styles/toggleButton.css
  src/app/Styles/userDetail.css
  src/app/Views/devices.html
  src/app/Views/settings.html
  src/app/Views/theme.html
  src/app/app.module.ts
  src/environments/environment.ts
  src/index.html
  src/sw.js
Labels: Bug, Enhancement, Invalid, New feature, Obsolete, Performance, Security

#274 fix an issue that IIS don't return json and woff2.
  src/web.config
Labels: Bug

#281 make ios native support better
  src/index.html
Labels: Enhancement

#283 Better dark theme look and upgrade version
  package.json
  src/app/Styles/add-friend.css
  src/app/Styles/conversations.css
  src/app/Styles/friends.css
  src/app/Styles/menu.css
  src/app/Styles/nav.css
  src/app/Styles/signin.css
  src/app/Styles/talking.css
  src/app/Views/signin.html
Labels: Enhancement

#289 Fix CSS grammar issue.
  src/app/Styles/menu.css
Labels: Enhancement

#286 Emergency release 3.0.1
  README.md
  package.json
  src/app/Controllers/settings.component.ts
  src/app/Controllers/signin.component.ts
  src/app/Services/CacheService.ts
  src/app/Styles/add-friend.css
  src/app/Styles/conversations.css
  src/app/Styles/friends.css
  src/app/Styles/menu.css
  src/app/Styles/nav.css
  src/app/Styles/signin.css
  src/app/Styles/talking.css
  src/app/Views/signin.html
  src/index.html
  src/sw.js
  src/web.config
Labels: Bug, Enhancement, Security

#297 Better dark
  src/app/Styles/toggleButton.css
Labels: Enhancement

#301 Add EdgeNeko to contributor list.
  package.json
Labels: Others

#311 Animation displays faster so won't be so annoying to the user.
  package-lock.json
  src/app/Styles/talking.css
Labels: Enhancement

#326 New logo.
  build/icon.ico
  package-lock.json
  src/assets/144x144.png
  src/assets/240x240.png
  src/assets/48x48.png
  src/assets/512x512.png
  src/assets/72x72.png
  src/favicon.ico
  src/index.js
  src/manifest.json
Labels: Enhancement

#333 Fix #314
  package-lock.json
  package.json
  src/polyfills.ts
Labels: Bug

#351 Only cache 20 minutes for static resources
  src/web.config
Labels: Bug, Enhancement

#357 Local Search
  README.md
  src/app/Controllers/conversations.component.ts
  src/app/Controllers/friends.component.ts
  src/app/Controllers/group.component.ts
  src/app/Controllers/localSearch.component.ts
  src/app/Controllers/settings.component.ts
  src/app/Controllers/user.component.ts
  src/app/Models/CacheModel.ts
  src/app/Modules/AppRoutingModule.ts
  src/app/Services/CacheService.ts
  src/app/Services/InitService.ts
  src/app/Services/MessageService.ts
  src/app/Views/friends.html
  src/app/Views/localSearch.html
  src/app/app.module.ts
Labels: New feature

#375 Better text
  .github/ISSUE_TEMPLATE/api_connect_request.md
  src/app/Controllers/add-friend.component.ts
  src/app/Views/add-friend.html
  src/app/Views/friends.html
Labels: Enhancement

#381 better color system.
  package-lock.json
  src/app/Controllers/add-friend.component.ts
  src/app/Styles/add-friend.scss
  src/app/Styles/reddot.scss
  src/app/Styles/themes/_dark.scss
  src/app/Styles/themes/_light.scss
  src/app/Styles/themes/_shared.scss
  src/app/Views/add-friend.html
Labels: Enhancement
