Repository AiursoftWeb/Kahla.App, pull requests merged in 2019-09, with the labels that each got.

#668 Remove standard sign in method.
  src/app/Controllers/signin.component.ts
  src/app/Services/AuthApiService.ts
  src/app/Styles/signin.scss
  src/app/Views/signin.html
Labels: Invalid design

#670 Release 3.7.1
  .editorconfig
  angular.json
  config.xml
  copy-assetlinks.sh
  package-lock.json
  package.json
  resources/android/icon/drawable-hdpi-icon.png
  resources/android/icon/drawable-ldpi-icon.png
  resources/android/icon/drawable-mdpi-icon.png
  resources/android/icon/drawable-xhdpi-icon.png
  resources/android/icon/drawable-xxhdpi-icon.png
  resources/android/icon/drawable-xxxhdpi-icon.png
  resources/android/splash/drawable-land-hdpi-screen.png
  resources/android/splash/drawable-land-ldpi-screen.png
  resources/android/splash/drawable-land-mdpi-screen.png
  resources/android/splash/drawable-land-xhdpi-screen.png
  resources/android/splash/drawable-land-xxhdpi-screen.png
  resources/android/splash/drawable-land-xxxhdpi-screen.png
  resources/android/splash/drawable-port-hdpi-screen.png
  resources/android/splash/drawable-port-ldpi-screen.png
  resources/android/splash/drawable-port-mdpi-screen.png
  resources/android/splash/drawable-port-xhdpi-screen.png
  resources/android/splash/drawable-port-xxhdpi-screen.png
  resources/android/splash/drawable-port-xxxhdpi-screen.png
  resources/icon.png
  resources/splash.png
  src/app/Controllers/conversations.component.ts
  src/app/Controllers/discover.component.ts
  src/app/Controllers/header.component.ts
  src/app/Controllers/register.component.ts
  src/app/Controllers/settings.component.ts
  src/app/Controllers/signin.component.ts
  src/app/Controllers/talking.component.ts
  src/app/Modules/AppRoutingModule.ts
  src/app/Services/AuthApiService.ts
  src/app/Services/ConversationApiService.ts
  src/app/Services/InitService.ts
  src/app/Services/MessageService.ts
  src/app/Styles/button.scss
  src/app/Styles/signin.scss
  src/app/Views/app.html
  src/app/Views/conversations.html
  src/app/Views/friends.html
  src/app/Views/group.html
  src/app/Views/header.html
  src/app/Views/register.html
  src/app/Views/signin.html
  src/app/Views/talking.html
  src/app/app.module.ts
  src/assetlinks.json
  src/index.html
  src/index.js
  src/sw.js
Labels: New release

#687 feat: better loading indicator
  src/app/Styles/header.scss
  src/app/Styles/talking.scss
  src/app/Views/header.html
  src/app/Views/talking.html
Labels: Bug

#688 fix: prevent leaving the red dot on when clicking the notification.
  src/app/Services/MessageService.ts
Labels: Bug

#690 feat: set the title before getting the conversation detail.
  src/app/Controllers/talking.component.ts
  src/app/Views/talking.html
Labels: Enhancement required, Invalid design

#691 Better load icon.
  src/app/Views/header.html
Labels: Enhancement required
