Repository AiursoftWeb/Kahla.App, pull requests merged in 2019-12, with the labels that each got.

#742 Add a theme: Communist revolution style.
  src/app/Models/Themes.ts
  src/app/Services/ThemeService.ts
  src/app/Styles/_themes.scss
  src/app/Styles/themes/_communist-dark.scss
  src/app/Styles/themes/_communist-light.scss
  src/app/Views/theme.html
Labels: New feature request

#744 Enable user select email and toggling developer tools.
  src/app/Styles/menu.scss
  src/index.js
Labels: Enhancement required

#750 Add a grass green(hat) theme.
  src/app/Models/Themes.ts
  src/app/Services/ThemeService.ts
  src/app/Styles/_themes.scss
  src/app/Styles/themes/_grass-dark.scss
  src/app/Styles/themes/_grass-light.scss
  src/app/Views/theme.html
Labels: Enhancement required

#754 Release 3.8.5
  package-lock.json
  package.json
  src/app/Controllers/friends.component.ts
  src/app/Controllers/group.component.ts
  src/app/Controllers/manageGroup.component.ts
  src/app/Controllers/settings.component.ts
  src/app/Controllers/share.component.ts
  src/app/Controllers/talking.component.ts
  src/app/Controllers/user.component.ts
  src/app/Models/Themes.ts
  src/app/Models/VersionViewModel.ts
  src/app/Services/CheckService.ts
  src/app/Services/FriendshipService.ts
  src/app/Services/MessageService.ts
  src/app/Services/ThemeService.ts
  src/app/Services/TimerService.ts
  src/app/Services/UploadService.ts
  src/app/Styles/_themes.scss
  src/app/Styles/menu.scss
  src/app/Styles/themes/_grass-dark.scss
  src/app/Styles/themes/_grass-light.scss
  src/app/Views/advanced-settings.html
  src/app/Views/theme.html
  src/index.html
  src/index.js
Labels: New release

#755 feat: redesigned theme setting page.
  src/app/Controllers/theme.component.ts
  src/app/Styles/menu.scss
  src/app/Styles/themes/_communist-dark.scss
  src/app/Styles/themes/_communist-light.scss
  src/app/Styles/themes/_dark.scss
  src/app/Styles/themes/_default-dark.scss
  src/app/Styles/themes/_default-light.scss
  src/app/Styles/themes/_grass-dark.scss
  src/app/Styles/themes/_grass-light.scss
  src/app/Styles/themes/_light.scss
  src/app/Styles/themes/_sakura-dark.scss
  src/app/Styles/themes/_sakura-light.scss
  src/app/Styles/themes/_violet-dark.scss
  src/app/Styles/themes/_violet-light.scss
  src/app/Views/theme.html
Labels: New feature request
