Repository AiursoftWeb/Kahla.App, pull requests merged in 2019-11, with the labels that each got.

#730 Fix #727
  src/app/Controllers/share.component.ts
  src/app/Controllers/talking.component.ts
  src/app/Services/ConversationApiService.ts
  src/app/Services/InitService.ts
  src/app/Services/UploadService.ts
  src/app/Views/talking.html
Labels: Enhancement required

#732 fix: transparent single emoji
  src/app/Styles/talking.scss
Labels: Bug

#733 Production release
  package-lock.json
  package.json
  src/app/Controllers/share.component.ts
  src/app/Controllers/talking.component.ts
  src/app/Helpers/Uuid.ts
  src/app/Models/Message.ts
  src/app/Services/ConversationApiService.ts
  src/app/Services/InitService.ts
  src/app/Services/MessageService.ts
  src/app/Services/UploadService.ts
  src/app/Styles/menu.scss
  src/app/Styles/talking.scss
  src/app/Views/talking.html
Labels: New release
