Repository AiursoftWeb/Kahla.App, pull requests merged in 2019-06, with the labels that each got.

#524 Repairing BUG, modifying the name and avatar of group chat, if you click Save again, you will have problems.
  src/app/Controllers/manageGroup.component.ts
Labels: Bug

#526 Release 3.5.0
  README.md
  package-lock.json
  package.json
  src/app/Controllers/add-friend.component.ts
  src/app/Controllers/conversations.component.ts
  src/app/Controllers/friendrequests.component.ts
  src/app/Controllers/friends.component.ts
  src/app/Controllers/group.component.ts
  src/app/Controllers/manageGroup.component.ts
  src/app/Controllers/user.component.ts
  src/app/Controllers/userDetail.component.ts
  src/app/Models/CacheModel.ts
  src/app/Models/DissolveEvent.ts
  src/app/Models/EventType.ts
  src/app/Models/GroupConversation.ts
  src/app/Models/GroupsResults.ts
  src/app/Modules/AppRoutingModule.ts
  src/app/Services/CacheService.ts
  src/app/Services/ConversationApiService.ts
  src/app/Services/FriendsApiService.ts
  src/app/Services/GroupsApiService.ts
  src/app/Services/InitService.ts
  src/app/Services/MessageService.ts
  src/app/Services/TimerService.ts
  src/app/Services/UploadService.ts
  src/app/Styles/add-friend.scss
  src/app/Styles/badge.scss
  src/app/Styles/friends.scss
  src/app/Styles/local-search.scss
  src/app/Styles/themes/_shared.scss
  src/app/Views/add-friend.html
  src/app/Views/friends.html
  src/app/Views/group.html
  src/app/Views/header.html
  src/app/Views/manageGroup.html
  src/app/Views/talking.html
  src/app/app.module.ts
Labels: New release

#540 Release 3.5.1
  config.xml
  package.json
  src/app/Controllers/app.component.ts
  src/app/Controllers/friendrequests.component.ts
  src/app/Controllers/localSearch.component.ts
  src/app/Services/MessageService.ts
  src/app/Styles/add-friend.scss
  src/app/Styles/local-search.scss
  src/app/Views/add-friend.html
  src/app/Views/conversations.html
  src/app/Views/localSearch.html
Labels: New release

#546 Fix floating shadow issue.
  src/app/Styles/_shared.scss
  src/app/Styles/app.scss
Labels: Enhancement required, Invalid design
