Repository AiursoftWeb/Kahla.App, pull requests merged in 2019-10, with the labels that each got.

#697 feat: allow choosing file type when dropping a file
  src/app/Controllers/talking.component.ts
  src/app/Models/FileType.ts
  src/app/Services/UploadService.ts
  src/sw.js
Labels: Enhancement required

#699 feat: allow customize if using enter to send message
  angular.json
  package-lock.json
  package.json
  src/app/Controllers/advanced-setting.component.ts
  src/app/Controllers/talking.component.ts
  src/app/Models/KahlaUser.ts
  src/app/Services/AuthApiService.ts
  src/app/Styles/menu.scss
  src/app/Views/about.html
  src/app/Views/add-friend.html
  src/app/Views/advanced-settings.html
  src/app/Views/devices.html
  src/app/Views/friends.html
  src/app/Views/group.html
  src/app/Views/header.html
  src/app/Views/manageGroup.html
  src/app/Views/nav.html
  src/app/Views/settings.html
  src/app/Views/share.html
  src/app/Views/talking.html
  src/app/Views/theme.html
  src/app/Views/user.html
  src/sw.js
Labels: New feature request

#702 Production Release
  angular.json
  package-lock.json
  package.json
  publish.sh
  src/app/Controllers/advanced-setting.component.ts
  src/app/Controllers/talking.component.ts
  src/app/Models/FileType.ts
  src/app/Models/KahlaUser.ts
  src/app/Services/AuthApiService.ts
  src/app/Services/MessageService.ts
  src/app/Services/UploadService.ts
  src/app/Styles/add-friend.scss
  src/app/Styles/conversations.scss
  src/app/Styles/header.scss
  src/app/Styles/menu.scss
  src/app/Styles/talking.scss
  src/app/Views/about.html
  src/app/Views/add-friend.html
  src/app/Views/advanced-settings.html
  src/app/Views/devices.html
  src/app/Views/friends.html
  src/app/Views/group.html
  src/app/Views/header.html
  src/app/Views/manageGroup.html
  src/app/Views/nav.html
  src/app/Views/settings.html
  src/app/Views/share.html
  src/app/Views/talking.html
  src/app/Views/theme.html
  src/app/Views/user.html
  src/polyfills.ts
  src/sw.js
  src/web.config
Labels: New release

#713 feat: allow detecting Edge Chromium in devices page.
  src/app/Services/CacheService.ts
  src/app/Views/devices.html
  src/sw.js
Labels: New feature request

#712 fix: message include '@' can be send now
  src/app/Services/MessageService.ts
Labels: Enhancement required

#725 Release 3.8.2?
  .vscode/launch.json
  README.md
  package-lock.json
  package.json
  src/app/Controllers/add-friend.component.ts
  src/app/Controllers/advanced-setting.component.ts
  src/app/Controllers/discover.component.ts
  src/app/Controllers/group.component.ts
  src/app/Controllers/manageGroup.component.ts
  src/app/Controllers/settings.component.ts
  src/app/Controllers/talking.component.ts
  src/app/Controllers/user.component.ts
  src/app/Controllers/userDetail.component.ts
  src/app/Models/Message.ts
  src/app/Services/CacheService.ts
  src/app/Services/InitService.ts
  src/app/Services/MessageService.ts
  src/app/Services/ProbeService.ts
  src/app/Services/TimerService.ts
  src/app/Services/UploadService.ts
  src/app/Styles/signin.scss
  src/app/Styles/talking.scss
  src/app/Styles/themes/_dark.scss
  src/app/Styles/themes/_light.scss
  src/app/Views/devices.html
  src/app/Views/header.html
  src/app/Views/talking.html
  src/app/app.module.ts
  src/app/values.ts
  src/sw.js
  tslint.json
Labels: New release
