Repository AiursoftWeb/Kahla.App, pull requests merged in 2020-02, with the labels that each got.

#782 Emergency release 3.9.1 for 3.9.0 has some issue that user can't talk new friend.
  package-lock.json
  package.json
  src/app/Controllers/talking.component.ts
  src/app/Services/MessageService.ts
Labels: New release

#789 Allow user to select not listing me in the search result.
  src/app/Controllers/advanced-setting.component.ts
  src/app/Models/KahlaUser.ts
  src/app/Services/AuthApiService.ts
  src/app/Views/advanced-settings.html
Labels: New feature request

#799 feat: add inputValidator for swal dialog
  src/app/Controllers/friends.component.ts
  src/app/Controllers/user.component.ts
  src/app/Services/FriendshipService.ts
Labels: Enhancement required

#800 This pull request will fix the gap between messages again.
  src/app/Styles/talking.scss
Labels: Enhancement required

#802 Release 3.9.2
  package.json
  src/app/Controllers/about.component.ts
  src/app/Controllers/advanced-setting.component.ts
  src/app/Controllers/friends.component.ts
  src/app/Controllers/share.component.ts
  src/app/Controllers/talking.component.ts
  src/app/Controllers/user.component.ts
  src/app/Models/KahlaUser.ts
  src/app/Services/AuthApiService.ts
  src/app/Services/CheckService.ts
  src/app/Services/ConversationApiService.ts
  src/app/Services/FriendshipService.ts
  src/app/Services/UploadService.ts
  src/app/Styles/app.scss
  src/app/Styles/nav.scss
  src/app/Styles/talking.scss
  src/app/Views/about.html
  src/app/Views/advanced-settings.html
  src/app/Views/settings.html
  src/app/Views/signin.html
Labels: New release

#804 Upgrade angular to v9
  angular.json
  package-lock.json
  package.json
  src/app/Controllers/manageGroup.component.ts
  src/app/Controllers/talking.component.ts
  src/app/Controllers/userDetail.component.ts
  src/polyfills.ts
Labels: dependencies

#806 fix: correct avatar position in edge classic.
  angular.json
  src/app/Styles/talking.scss
Labels: Bug
